"""initial

Revision ID: f754c7e979b6
Revises: 
Create Date: 2026-08-15 13:27:36.785093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f754c7e979b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('licence', sa.Enum('ODBL', 'CC_BY_SA', 'LICENCE_OUVERTE', 'DOMAINE_PUBLIC', name='licence_type'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('date_dernier_import', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_reglementaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type_zone', sa.String(length=100), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('autorite', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_document', sa.String(length=500), nullable=True),
    sa.Column('date_arrete', sa.Date(), nullable=True),
    sa.Column('date_verification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('poi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('eau', 'refuge', 'camping', 'commerce', name='typepoi'), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('date_import', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_verficiation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('regle_bivouac',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=True),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('distance_min_route_m', sa.Integer(), nullable=True),
    sa.Column('contraintes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('texte_officiel', sa.String(), nullable=False),
    sa.Column('periode_validite', postgresql.DATERANGE(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone_reglementaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('type_obs', sa.String(length=50), nullable=False),
    sa.Column('valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auteur_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation')
    op.drop_table('regle_bivouac')
    op.drop_table('poi')
    op.drop_table('zone_reglementaire')
    op.drop_table('source')
    # ### end Alembic commands ###
